use super::{FocusPanel, View};

#[derive(Debug, Clone)]
pub enum Action {
    Paste(String),
    HelpOpen,
    HelpClose,
    HelpScroll(i16),
    ErrorClear,
    ConfirmDeleteOpen,
    ConfirmDeleteSelect(bool),
    ConfirmDeleteConfirm,
    ConfirmDeleteCancel,
    ConfirmQuitOpen,
    ConfirmQuitSelect(bool),
    ConfirmQuitConfirm,
    ConfirmQuitCancel,
    ViewSet(View),
    FocusToggle,
    FocusSet(FocusPanel),
    MoveSelection(isize),
    MoveFilter(isize),
    SetFilter(usize),
    TogglePause,
    StartAdd,
    InputChar(char),
    InputBackspace,
    InputDelete,
    InputLeft,
    InputRight,
    InputHome,
    InputEnd,
    InputEnter,
    InputCancel,
    FilePickerUp,
    FilePickerDown,
    FilePickerToggle,
    FilePickerAll,
    FilePickerNone,
    FilePickerConfirm,
    FilePickerCancel,
    Refresh,
    RunEffect(super::effect::Effect),
}
